### ISSUE TITLE
Review for release

### ISSUE THREAD

**Issue by pepeiborra** [pepeiborra/haskell-src-exts-util#1]
Needed for releasing arrowp-qq v0.2.0 providing a haskell-src-exts preprocessor

**Comment by ndmitchell** [comment]
Since I am looking at the code for the first time in a while, I thought I'd just write down all my thoughts. That doesn't mean leaving it as is, and releasing now, isn't the right way forward.

### Util

Good call not to expose Util. It's a bit of a grab-bag of gunk. My guess is you'd want to make a bunch of these things Prism.

### Type

* `type S = SrcSpanInfo` is a bit ambiguous. Perhaps `type SL = SrcLoc`, `type SSI = SrcSpanInfo` and `type SS = SrcSpan`? Or maybe these short aliases aren't too important? But they are reasonably long, so perhaps.
* Ditto, is `Module_` very helpful? It is in HLint where all modules are `Module SSI`, but more generally it just makes HLint clearer, not other libraries.
* Why is HasSrcLoc a type class? Why not just a type family? What is the relationship to Annotated class? Is it in many ways just `Unapply` on any arbitrary type constructor, with the restriction that `Annotated (Unapply x)`? Does `Unapply` already exist?
* `nullSrcLoc` etc are all just `Default` instances for the location types. Having them be real defaults with `Default` type class would be way clearer - I can never remember if `an` is the `SSI` or the `SL`, or how to get from one to the other.

### Bracket

* `descendBracket` has a `Bool` in it. The docs don't say what it does. What does it do? Seems important...

### FreeVars

* I see why you introduced `HasSrcLoc`, but `allVars :: ast l -> Vars l` would be simpler and cleaner - unconvinced `HasSrcLoc` is useful.

**Comment by pepeiborra** [comment]
Thanks for the sober review! 

## Util
Is there because it is needed by the other modules and rewriting solid code using lenses is not worth the effort.
- [x] Run Weeder on this module before release.

## Type
- Not sure why I brought the type synonyms over, but you are right - they belong in HLint but not in a general purpose library like this.
-  `HasSrcLoc` is an associated type family because unassociated ones are evil; the argument is in the `Constrained type families` paper. Moreover, the HasSrcLoc type class should eventually grow a member `srcLoc :: Lens a (SrcLocType a)`. 
- The `Annotated` class is too restrictive unfortunately, since not all the relevant `FreeVars` instances are functors. For example the set of free vars of an `[Stmt l]` is not `foldMap freeVars` over the list of statements but something completely different. Maybe a better name would be `AnnotatedType` with views to replacing the `Annotated` class ?
- [x]  Rename `HasSrcLoc` to ~~AnnotatedType~~ `Located` and ~~SrcLocType~~ to `Loc`.

## Bracket
- `descendBracket` is internal, so I have little motivation to improve the comments. One thing that could help future maintainers of this package would be the vcs history of the modules, if only we had a Git expert around..
- [ ] Retrieve the git history from the original modules in HLint.

## Module structure
- After removing the type synonyms and the null src loc values from the `Type` module the only thing left is the `HasSrcLoc` type class. My aim is to move it into an internal module, make all the other modules internal, and then reexpose everything from a `Language.Haskell.Exts.Util` module.

## HLint
- Once this is in Hackage, we should change Hlint to use it, assuming that there isn't a negative impact in performance. Are there any tests that need to be extracted too ?
- [ ] Propagate changes to HLint

**Comment by ndmitchell** [comment]
Annotated seems much more sensible now, with your proposed changes and notes.

I wouldn't bother getting the original HLint history for the code - I'd just link back to where they originally lived, as of the commit you copied them over. I doubt the history is that meaningful - other than for links to issues - and I tend to write those in the code where they really matter.

It's highly unlikely there will be a negative impact on performance moving HLint to this code - none of it is on the critical path. Before converting HLint to use it, we should probably consider what (if anything) can move into haskell-src-exts proper. Your annotated type class seems like a plausible candidate?

Most of the HLint tests are at the level of HLint, so test these code paths higher up the stack. Having a few tests seems sensible.

**Comment by pepeiborra** [comment]
I'm reluctant to propose additions to haskell-src-exts - it's a large library with lots of users and therefore the bar for the `Annotated` kind of change is quite high. I'd rather let the new class live in a new package and promote it only if/when enough people are bothered by the warts in the old one.

**Comment by ndmitchell** [comment]
Makes sense - I can see the value in that.
